### PR TITLE
Fix client.adapt behavior for OpenShiftClient on OpenShift 4

### PR DESCRIPTION
**Pull request by apupier**
OpenshiftAdapterSupport hits `/apis` endpoint for getting list of
available APIGroups. This fails for OpenShift 4 since OpenShift 4 gives
403. Modify OpenShiftAdapterSupport.isOpenShiftAPIGroups to use
OkHttpClient instance with added `OpenShiftOAuthInterceptor`

relates to https://issues.redhat.com/browse/ENTESB-15700

### CODE REVIEW

**Comment by apupier** [comment]
@rohanKanojia can you check that I backported the fix correctly please?

**Comment by rohanKanojia** [comment]
Fix for this issue is just[ this line in OpenShiftAdapterSupport](https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftAdapterSupport.java#L70) which seems to be ported correctly. 

Looks good to me :+1:

**Comment by apupier** [comment]
put @grgrzybek and @cunningt as reviewer from Fuse team as you were last committers on this project. Please redirect me to somebody else if needed.

**Review by cunningt — APPROVED** [review]
Looks good to me!

**Pull request merged**
